import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header'; import Footer from '@/components/Footer'; import FloatingContact from '@/components/FloatingContact'; import ReduxProvider from '@/components/ReduxProvider';
const manrope=Manrope({subsets:['latin','latin-ext'],variable:'--font-manrope'});
const siteUrl=process.env.NEXT_PUBLIC_SITE_URL||'https://gumusogluelektrik.com';
const schema={'@context':'https://schema.org','@type':'Electrician',name:'Gümüşoğlu Elektrik',url:siteUrl,telephone:'+90 538 468 23 99',email:'ozkagum@gmail.com',foundingDate:'1974',description:'Akkuş ve çevresinde elektrik malzemeleri, tesisat, taahhüt, plan, proje, abonelik ve danışmanlık hizmetleri.',address:{'@type':'PostalAddress',streetAddress:'İstiklal Caddesi Merkez Mahallesi No: 43/A',addressLocality:'Akkuş',addressRegion:'Ordu',addressCountry:'TR'},sameAs:['https://www.instagram.com/gumusogluelektrik?igsi=bmMyYTVqZ2E4aW1u','https://www.facebook.com/share/19JMbqnJZk/']};
export const metadata:Metadata={metadataBase:new URL(siteUrl),title:'Gümüşoğlu Elektrik | Akkuş, Ordu',description:'1974’ten bu yana elektrik malzemeleri, tesisat, taahhüt, plan, proje, abonelik ve danışmanlık hizmetleri.',keywords:['Gümüşoğlu Elektrik','Akkuş elektrikçi','Ordu elektrik','elektrik malzemeleri','elektrik tesisatı','elektrik projesi','abonelik işlemleri'],openGraph:{title:'Gümüşoğlu Elektrik | 1974’ten Beri Güvenle',description:'Akkuş ve çevresinde güvenli ve kaliteli enerji çözümleri.',images:[{url:'/gumusoglu/hero-gumusoglu-light-v3.webp',width:1536,height:1024}]}};
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="tr"><head><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></head><body className={`${manrope.variable} font-sans`}><ReduxProvider><Header/>{children}<Footer/><FloatingContact/></ReduxProvider></body></html>}
