import Image from 'next/image';
import Link from 'next/link';
import { FiArrowDown, FiArrowRight, FiCheck, FiClock, FiMapPin, FiPhone, FiShield, FiTool } from 'react-icons/fi';
import { services, process } from '@/data/site';
import { getPublishedGallery, getPublishedPosts } from '@/lib/publicContent';

export default async function Home(){const [blogPosts,galleryData]=await Promise.all([getPublishedPosts(),getPublishedGallery()]);const gallery=galleryData.slice(0,3).map((item,index)=>({...item,label:item.title,className:index===0?'lg:col-span-7 lg:row-span-2':'lg:col-span-5'}));return <main className="overflow-hidden">
  {/* 1 — Hero */}
  <section className="relative flex min-h-[860px] items-end overflow-hidden bg-[#1c2d49] px-5 pb-20 pt-28 text-white sm:px-8 lg:min-h-screen lg:px-14 lg:pb-24">
    <Image src="/gumusoglu/hero-gumusoglu-light-v3.webp" alt="Gümüşoğlu Elektrik uzmanı pano kontrolü yaparken" fill priority className="object-cover object-[66%_center]" sizes="100vw"/>
    <div className="absolute inset-0 bg-black/25"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(17,31,44,.58)_0%,rgba(17,31,44,.34)_45%,rgba(17,31,44,.05)_82%)]"/><div className="absolute inset-0 bg-gradient-to-t from-[#14283e]/50 via-transparent to-transparent"/>
    <div className="relative mx-auto w-full max-w-[1500px]"><div className="max-w-4xl"><div className="mb-7 inline-flex items-center gap-3 rounded-full border border-white/25 bg-white/10 px-4 py-2 text-[10px] font-extrabold uppercase tracking-[.19em] backdrop-blur-md"><span className="h-2 w-2 rounded-full bg-[#77c3be]"/> 1974&apos;ten beri Akkuş&apos;un enerjisi</div><h1 className="text-[52px] font-black leading-[.94] tracking-[-.06em] sm:text-[76px] lg:text-[96px]">Yarım asırlık<br/>tecrübe. <span className="text-[#a8d5ed]">Tek güç.</span></h1><p className="mt-7 max-w-2xl text-base font-medium leading-8 text-white/78 sm:text-lg">Elektrik malzemelerinden anahtar teslim uygulamaya; plan, proje, taahhüt, abonelik ve danışmanlıkta güvenilir çözüm ortağınız.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/hizmetlerimiz" className="inline-flex items-center justify-center gap-3 rounded-xl bg-[#347bb7] px-7 py-4 text-sm font-black shadow-[0_14px_35px_rgba(16,42,68,.25)] transition hover:-translate-y-1 hover:bg-[#286796]">Hizmetlerimizi keşfedin <FiArrowRight/></Link><a href="tel:+905384682399" className="inline-flex items-center justify-center gap-3 rounded-xl border border-white/30 bg-white/10 px-7 py-4 text-sm font-black backdrop-blur-md transition hover:bg-white/20"><FiPhone/> 0538 468 23 99</a></div></div><div className="mt-14 flex items-center gap-3 text-[10px] font-black uppercase tracking-[.18em] text-white/55"><FiArrowDown/> Aşağı kaydırın</div></div>
  </section>

  {/* 2 — Güven göstergeleri */}
  <section className="border-b border-[#cbdbe7] bg-[#e8f1f7] px-5 sm:px-8 lg:px-14"><div className="mx-auto grid max-w-[1500px] grid-cols-2 divide-x divide-[#c7d9e6] lg:grid-cols-4"><div className="py-8 pr-5"><b className="text-3xl font-black text-[#347bb7] sm:text-4xl">50+</b><p className="mt-2 text-xs font-bold text-[var(--muted)]">Yıllık sektör tecrübesi</p></div><div className="px-5 py-8"><b className="text-3xl font-black text-[#45a0a0] sm:text-4xl">1974</b><p className="mt-2 text-xs font-bold text-[var(--muted)]">Kuruluş yılı</p></div><div className="px-5 py-8"><b className="text-3xl font-black text-[#776eb4] sm:text-4xl">6</b><p className="mt-2 text-xs font-bold text-[var(--muted)]">Uzmanlık alanı</p></div><div className="px-5 py-8"><b className="text-3xl font-black text-[#347bb7] sm:text-4xl">360°</b><p className="mt-2 text-xs font-bold text-[var(--muted)]">Anahtar teslim çözüm</p></div></div></section>

  {/* 3 — Hizmetler */}
  <section className="bg-[#f4f7fa] px-5 py-24 sm:px-8 lg:px-14 lg:py-28"><div className="mx-auto max-w-[1500px]"><div className="flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><div><p className="eyebrow">Hizmetlerimiz</p><h2 className="mt-5 text-4xl font-black leading-[1.02] tracking-[-.05em] sm:text-6xl">Enerjinin olduğu<br/>her yerde.</h2></div><div><p className="max-w-xl text-base leading-8 text-[var(--muted)]">Doğru malzemeden güvenli uygulamaya, teknik projeden resmi süreçlere kadar her aşamada yanınızdayız.</p><Link href="/hizmetlerimiz" className="mt-5 inline-flex items-center gap-2 text-sm font-black text-[#347bb7]">Tüm hizmetleri inceleyin <FiArrowRight/></Link></div></div><div className="mt-12 grid auto-rows-[300px] gap-5 md:grid-cols-2 lg:grid-cols-12">{services.map(({image,icon:Icon,title,short},i)=><Link href="/hizmetlerimiz" key={title} className={`group relative overflow-hidden rounded-[28px] ${i===0?'lg:col-span-7 lg:row-span-2':i===1?'lg:col-span-5 lg:row-span-2':'lg:col-span-3'}`}><Image src={image} alt={title} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width:1024px) 100vw,55vw"/><div className="absolute inset-0 bg-gradient-to-t from-[#132d43]/85 via-[#173b59]/18 to-transparent"/><span className="absolute right-5 top-5 flex h-11 w-11 items-center justify-center rounded-xl border border-white/25 bg-white/15 text-white backdrop-blur-md"><Icon/></span><div className="absolute inset-x-0 bottom-0 p-6 text-white sm:p-8"><span className="text-[10px] font-black uppercase tracking-[.16em] text-white/55">0{i+1} / Hizmet</span><h3 className={`${i<2?'mt-3 text-3xl sm:text-4xl':'mt-2 text-xl'} font-black tracking-[-.035em]`}>{title}</h3><p className={`mt-3 max-w-md leading-6 text-white/68 ${i<2?'text-sm':'hidden text-xs xl:block'}`}>{short}</p><FiArrowRight className="mt-5 transition group-hover:translate-x-1"/></div></Link>)}</div></div></section>

  {/* 4 — Kurumsal hikâye */}
  <section className="bg-[#dceaf3] px-5 py-20 sm:px-8 lg:px-14 lg:py-24"><div className="mx-auto grid max-w-[1500px] overflow-hidden rounded-[34px] bg-white shadow-[0_26px_70px_rgba(46,83,117,.1)] lg:grid-cols-[1.08fr_.92fr]"><div className="relative min-h-[470px] lg:min-h-[650px]"><Image src="/gumusoglu/electrical-store.webp" alt="Gümüşoğlu Elektrik mağazası" fill className="object-cover" sizes="(max-width:1024px) 100vw,55vw"/><div className="absolute inset-0 bg-gradient-to-t from-[#1f557d]/45 via-transparent to-transparent"/><div className="absolute bottom-7 left-7 rounded-2xl bg-white/92 px-6 py-5 shadow-xl backdrop-blur"><b className="text-4xl font-black text-[#347bb7]">1974</b><span className="ml-4 text-xs font-black uppercase tracking-[.15em] text-[var(--muted)]">Başlangıç</span></div></div><div className="flex flex-col justify-center p-8 sm:p-12 lg:p-16"><p className="eyebrow">Hikâyemiz</p><h2 className="mt-5 text-4xl font-black leading-tight tracking-[-.05em] sm:text-5xl">Geçmişten aldığımız güçle geleceği aydınlatıyoruz.</h2><p className="mt-6 text-base leading-8 text-[var(--muted)]">Gerçek Elektrik adıyla başlayan yolculuğumuzu 1999&apos;dan bu yana Gümüşoğlu Elektrik olarak sürdürüyor; köklü birikimimizi güncel teknoloji ve güvenlik standartlarıyla buluşturuyoruz.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{['Doğru malzeme','Nitelikli işçilik','Güvenli uygulama','Zamanında teslim'].map(x=><span key={x} className="flex items-center gap-3 text-sm font-bold"><FiCheck className="text-[#45a0a0]"/>{x}</span>)}</div><Link href="/hakkimizda" className="mt-9 inline-flex w-fit items-center gap-2 rounded-xl bg-[#edf4f8] px-6 py-4 text-sm font-black text-[#347bb7]">Bizi yakından tanıyın <FiArrowRight/></Link></div></div></section>

  {/* 5 — Süreç */}
  <section className="bg-[#dfeaf2] px-5 py-20 sm:px-8 lg:px-14 lg:py-24"><div className="mx-auto grid max-w-[1500px] overflow-hidden rounded-[34px] bg-[#1f5278] shadow-[0_28px_80px_rgba(31,82,120,.18)] lg:grid-cols-[.86fr_1.14fr]"><div className="relative min-h-[480px] lg:min-h-[760px]"><Image src="/gumusoglu/project-planning.webp" alt="Gümüşoğlu Elektrik proje planlama süreci" fill className="object-cover" sizes="(max-width:1024px) 100vw,44vw"/><div className="absolute inset-0 bg-gradient-to-t from-[#153c59]/75 via-transparent to-transparent"/><div className="absolute bottom-8 left-8 right-8 text-white"><span className="text-[10px] font-black uppercase tracking-[.18em] text-[#b9deee]">Fikirden enerjiye</span><h2 className="mt-3 text-4xl font-black tracking-[-.05em]">Planlı başlar.<br/>Eksiksiz biter.</h2></div></div><div className="p-7 text-white sm:p-10 lg:p-14"><p className="text-[11px] font-black uppercase tracking-[.2em] text-[#a8d5ed]">Çalışma sürecimiz</p><p className="mt-4 max-w-xl text-sm leading-7 text-white/65">Keşiften teslimata kadar her adımı şeffaf, ölçülebilir ve kontrol edilebilir biçimde yönetiyoruz.</p><ol className="relative mt-9 border-l border-white/18">{process.map(([no,title,text],i)=><li key={no} className="group relative grid grid-cols-[54px_1fr] gap-4 border-b border-white/12 py-6 pl-7 last:border-0"><span className="absolute -left-[7px] top-8 h-[13px] w-[13px] rounded-full border-[3px] border-[#1f5278] bg-[#91c8d4]"/><span className="text-sm font-black text-[#a8d5ed]">{no}</span><div><div className="flex items-center justify-between"><h3 className="text-xl font-black">{title}</h3>{i<4&&<FiArrowRight className="text-white/30 transition group-hover:translate-x-1 group-hover:text-white"/>}</div><p className="mt-2 text-sm leading-6 text-white/58">{text}</p></div></li>)}</ol></div></div></section>

  {/* 6 — Galeri */}
  <section className="bg-[#f4f1f8] px-5 py-24 sm:px-8 lg:px-14 lg:py-28"><div className="mx-auto max-w-[1500px]"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="eyebrow">Galeriden</p><h2 className="mt-5 text-4xl font-black tracking-[-.05em] sm:text-5xl">İşimizin içinden.</h2></div><Link href="/galeri" className="inline-flex items-center gap-2 text-sm font-black text-[#6d63a8]">Tüm galeriyi görün <FiArrowRight/></Link></div><div className="mt-12 grid auto-rows-[270px] gap-5 lg:grid-cols-12">{gallery.map(item=><Link href="/galeri" key={item.id} className={`group relative overflow-hidden rounded-[26px] ${item.className}`}><Image src={item.src} alt={item.label} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width:1024px) 100vw,60vw"/><div className="absolute inset-0 bg-gradient-to-t from-[#172d44]/65 via-transparent to-transparent"/><div className="absolute bottom-0 left-0 p-6 text-white"><span className="text-[10px] font-black uppercase tracking-[.16em] text-white/60">{item.tag}</span><h3 className="mt-2 text-xl font-black">{item.label}</h3></div></Link>)}</div></div></section>

  {/* 7 — Haberler / Blog */}
  <section className="bg-[#eaf2f7] px-5 py-24 sm:px-8 lg:px-14 lg:py-28"><div className="mx-auto max-w-[1500px]"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="eyebrow">Haberler & Bilgi</p><h2 className="mt-5 text-4xl font-black tracking-[-.05em] sm:text-5xl">Elektriğe dair güncel bilgiler.</h2></div><Link href="/blog" className="inline-flex items-center gap-2 text-sm font-black text-[#347bb7]">Tüm yazılar <FiArrowRight/></Link></div><div className="mt-12 grid gap-6 lg:grid-cols-3">{blogPosts.slice(0,3).map(post=><Link href={`/blog/${post.slug}`} key={post.slug} className="group overflow-hidden rounded-[26px] bg-white shadow-[0_12px_35px_rgba(46,83,117,.07)]"><div className="relative min-h-[240px] overflow-hidden"><Image src={post.image} alt={post.title} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width:1024px) 100vw,33vw"/></div><div className="p-7"><div className="flex items-center justify-between text-[10px] font-black uppercase tracking-[.14em]"><span className="text-[#347bb7]">{post.category}</span><span className="flex items-center gap-2 text-[var(--muted)]"><FiClock/>{post.readTime}</span></div><h3 className="mt-5 text-xl font-black leading-7">{post.title}</h3><p className="mt-3 text-sm leading-7 text-[var(--muted)]">{post.excerpt}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-black text-[#347bb7]">Devamını okuyun <FiArrowRight/></span></div></Link>)}</div></div></section>

  {/* 8 — İletişim */}
  <section className="bg-[#edf3f7] px-5 py-20 sm:px-8 lg:px-14 lg:py-24"><div className="relative mx-auto min-h-[620px] max-w-[1500px] overflow-hidden rounded-[34px] text-white shadow-[0_28px_80px_rgba(31,82,120,.16)]"><Image src="/gumusoglu/service-installation-v1.webp" alt="Gümüşoğlu Elektrik iletişim" fill className="object-cover object-center" sizes="100vw"/><div className="absolute inset-0 bg-[#173d5b]/60"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(20,57,84,.92)_0%,rgba(20,57,84,.72)_48%,rgba(20,57,84,.25)_100%)]"/><div className="relative flex min-h-[620px] items-center p-8 sm:p-12 lg:p-16"><div className="max-w-2xl"><p className="text-[11px] font-black uppercase tracking-[.2em] text-[#a8d5ed]">İletişim</p><h2 className="mt-5 text-4xl font-black leading-[1.03] tracking-[-.05em] sm:text-6xl">Projenize birlikte<br/>enerji verelim.</h2><p className="mt-6 max-w-xl text-base leading-8 text-white/70">Malzeme, tesisat, proje veya abonelik ihtiyacınız için bizi arayın; doğru çözümü birlikte belirleyelim.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/iletisim" className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-7 py-4 text-sm font-black text-[#347bb7]">İletişim sayfası <FiArrowRight/></Link><a href="tel:+905384682399" className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/25 bg-white/10 px-7 py-4 text-sm font-black backdrop-blur"><FiPhone/> 0538 468 23 99</a></div><a href="https://maps.google.com/?q=İstiklal+Caddesi+Merkez+Mahallesi+No+43+A+Akkuş+Ordu" target="_blank" rel="noopener noreferrer" className="mt-10 flex items-start gap-4 rounded-2xl border border-white/15 bg-white/10 p-5 backdrop-blur sm:w-fit"><FiMapPin className="mt-1 shrink-0 text-[#a8d5ed]"/><div><small className="text-[9px] font-black uppercase tracking-[.16em] text-white/45">Adresimiz</small><b className="mt-1 block text-sm leading-6">İstiklal Cad. Merkez Mah. No: 43/A, Akkuş / Ordu</b></div></a></div></div></div></section>
</main>}
