import Image from 'next/image';
import Link from 'next/link';
import { FiArrowRight, FiCheckCircle, FiClock, FiShield, FiTool } from 'react-icons/fi';

export function TrustBand(){const items=[['50+','Yıllık deneyim'],['1974','Kuruluş yılı'],['6','Uzmanlık alanı'],['360°','Tek elden çözüm']];return <section className="border-y border-[#eadadb] bg-[#fff2f3] px-5 sm:px-8 lg:px-14"><div className="mx-auto grid max-w-[1500px] grid-cols-2 divide-x divide-[#eadadb] lg:grid-cols-4">{items.map(([value,label])=><div key={label} className="px-5 py-8 first:pl-0"><b className="text-3xl font-black text-[#e30613] sm:text-4xl">{value}</b><p className="mt-2 text-xs font-bold text-[var(--muted)]">{label}</p></div>)}</div></section>}

export function PrinciplesBand(){const items=[{icon:FiShield,title:'Güvenli uygulama',text:'Güncel standartlara ve doğru koruma yöntemlerine bağlı çalışma.'},{icon:FiTool,title:'Nitelikli işçilik',text:'Deneyimli ekip, düzenli saha ve detaylı son kontrol.'},{icon:FiClock,title:'Zamanında teslim',text:'Gerçekçi iş programı ve her aşamada açık bilgilendirme.'}];return <section className="bg-[#faf7f7] px-5 py-20 sm:px-8 lg:px-14"><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="eyebrow justify-center">Hizmet anlayışımız</p><h2 className="mt-5 text-4xl font-black tracking-[-.05em]">Her işte aynı özen.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{items.map(({icon:Icon,title,text},i)=><article key={title} className="rounded-[24px] border border-white/70 bg-white/75 p-7 shadow-sm backdrop-blur"><span className={`flex h-12 w-12 items-center justify-center rounded-xl ${i===1?'bg-[#fff0f1] text-[#c8101b]':i===2?'bg-[#f7e8e9] text-[#c8101b]':'bg-[#fff0f1] text-[#e30613]'}`}><Icon/></span><h3 className="mt-6 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-7 text-[var(--muted)]">{text}</p></article>)}</div></div></section>}

export function ImageCta({eyebrow,title,text,image,href='/iletisim',label='İletişime geçin'}:{eyebrow:string;title:string;text:string;image:string;href?:string;label?:string}){return <section className="bg-[#fafafa] px-5 py-20 sm:px-8 lg:px-14"><div className="relative mx-auto min-h-[440px] max-w-[1500px] overflow-hidden rounded-[32px] text-white"><Image src={image} alt={title} fill className="object-cover" sizes="100vw"/><div className="absolute inset-0 bg-[#202022]/55"/><div className="absolute inset-0 bg-gradient-to-r from-[#202022]/90 via-[#202022]/55 to-transparent"/><div className="relative flex min-h-[440px] items-center p-8 sm:p-12 lg:p-16"><div className="max-w-2xl"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#ffafb3]">{eyebrow}</p><h2 className="mt-5 text-4xl font-black leading-tight tracking-[-.05em] sm:text-5xl">{title}</h2><p className="mt-5 max-w-xl text-sm leading-7 text-white/70">{text}</p><Link href={href} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-white px-6 py-4 text-sm font-black text-[#e30613]">{label}<FiArrowRight/></Link></div></div></div></section>}

export function AssuranceList(){return <section className="bg-[#f5eeee] px-5 py-16 sm:px-8 lg:px-14"><div className="mx-auto grid max-w-[1500px] gap-5 md:grid-cols-3">{['İhtiyacı doğru analiz ederiz','Süreci açıkça paylaşırız','Teslim öncesi kontrol ederiz'].map(x=><div key={x} className="flex items-center gap-4 rounded-2xl bg-white p-6 font-black"><FiCheckCircle className="h-5 w-5 shrink-0 text-[#ef1b18]"/>{x}</div>)}</div></section>}
