import { FiFacebook, FiInstagram, FiMail, FiMapPin, FiMessageCircle, FiPhone } from 'react-icons/fi';
import SitePageHero from '@/components/SitePageHero';

const rows=[
  {icon:FiPhone,label:'Telefon',value:'0538 468 23 99',href:'tel:+905384682399'},
  {icon:FiMessageCircle,label:'WhatsApp',value:'Hızlı mesaj gönderin',href:'https://wa.me/905384682399'},
  {icon:FiMail,label:'E-posta',value:'ozkagum@gmail.com',href:'mailto:ozkagum@gmail.com'},
  {icon:FiMapPin,label:'Adres',value:'İstiklal Cad. Merkez Mah. No: 43/A Akkuş / Ordu',href:'https://maps.google.com/?q=İstiklal+Caddesi+Merkez+Mahallesi+No+43+A+Akkuş+Ordu'},
];
export default function ContactPage(){return <main><SitePageHero eyebrow="İletişim" title="Projenizi birlikte değerlendirelim." description="Malzeme, tesisat, proje, taahhüt veya abonelik ihtiyacınız için size en uygun kanaldan bize ulaşın." image="/gumusoglu/hero-gumusoglu-light-v3.webp"/><section className="px-5 py-20 sm:px-8 lg:px-14 lg:py-28"><div className="mx-auto grid max-w-[1500px] gap-10 lg:grid-cols-[1.05fr_.95fr]"><div><p className="eyebrow">Bize ulaşın</p><h2 className="mt-5 text-4xl font-black tracking-[-.05em]">Size nasıl yardımcı olabiliriz?</h2><p className="mt-5 max-w-xl text-base leading-8 text-[var(--muted)]">İhtiyacınızı kısaca paylaşın; doğru malzeme, uygulama veya süreç için sizi yönlendirelim.</p><div className="mt-9 grid gap-4 sm:grid-cols-2">{rows.map(({icon:Icon,label,value,href})=><a key={label} href={href} target={href.startsWith('http')?'_blank':undefined} rel={href.startsWith('http')?'noopener noreferrer':undefined} className="rounded-[22px] border border-[var(--line)] bg-white p-6 transition hover:-translate-y-1 hover:shadow-lg"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#e7f1f8] text-[#347bb7]"><Icon/></span><small className="mt-5 block text-[10px] font-black uppercase tracking-[.16em] text-[var(--muted)]">{label}</small><b className="mt-2 block text-sm leading-6">{value}</b></a>)}</div></div><div className="rounded-[28px] bg-[#347bb7] p-8 text-white sm:p-10"><p className="text-xs font-black uppercase tracking-[.18em] text-white/60">Gümüşoğlu Elektrik</p><h2 className="mt-4 text-3xl font-black">Akkuş&apos;ta, size yakın.</h2><p className="mt-5 text-sm leading-7 text-white/70">Mağazamızı ziyaret ederek ürünleri inceleyebilir, projeniz için yüz yüze bilgi alabilirsiniz.</p><a href="https://maps.google.com/?q=İstiklal+Caddesi+Merkez+Mahallesi+No+43+A+Akkuş+Ordu" target="_blank" rel="noopener noreferrer" className="mt-8 flex min-h-[220px] items-center justify-center rounded-[20px] border border-white/20 bg-[linear-gradient(135deg,#2b689b,#45a0a0)] p-8 text-center"><div><FiMapPin className="mx-auto h-9 w-9"/><b className="mt-5 block">İstiklal Caddesi, Merkez Mahallesi<br/>No: 43/A Akkuş / Ordu</b><span className="mt-3 block text-xs text-white/65">Haritada yol tarifi alın</span></div></a><div className="mt-7 flex gap-3"><a href="https://www.instagram.com/gumusogluelektrik?igsi=bmMyYTVqZ2E4aW1u" target="_blank" rel="noopener noreferrer" className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/10"><FiInstagram/></a><a href="https://www.facebook.com/share/19JMbqnJZk/" target="_blank" rel="noopener noreferrer" className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/10"><FiFacebook/></a></div></div></div></section></main>}
