import Image from 'next/image';
import Link from 'next/link';
import { FiArrowRight, FiCheck } from 'react-icons/fi';
import SitePageHero from '@/components/SitePageHero';
import { ImageCta, PrinciplesBand, TrustBand } from '@/components/PageExtras';
import { process, services } from '@/data/site';

export default function ServicesPage(){return <main><SitePageHero eyebrow="Hizmetlerimiz" title="Enerjinin olduğu her yerde." description="Malzeme tedariğinden projelendirmeye, uygulamadan abonelik süreçlerine kadar elektrik işlerinizin tüm aşamalarını tek elden yönetiyoruz." image="/gumusoglu/service-installation-v1.webp"/>
  <section className="bg-[#f1f6f9] px-5 py-20 sm:px-8 lg:px-14 lg:py-28"><div className="mx-auto max-w-[1500px]"><div className="grid gap-6 md:grid-cols-2">{services.map(({image,icon:Icon,title,text,items},i)=><article key={title} className="group overflow-hidden rounded-[28px] bg-white shadow-[0_14px_42px_rgba(46,83,117,.07)]"><div className="relative min-h-[300px] overflow-hidden"><Image src={image} alt={title} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width:768px) 100vw,50vw"/><div className="absolute inset-0 bg-gradient-to-t from-[#173b59]/45 via-transparent to-transparent"/><span className="absolute left-6 top-6 flex h-12 w-12 items-center justify-center rounded-xl border border-white/40 bg-white/85 text-[#347bb7] backdrop-blur"><Icon/></span><span className="absolute right-6 top-6 text-xs font-black text-white">0{i+1}</span></div><div className="p-7 sm:p-9"><h2 className="text-3xl font-black tracking-[-.04em]">{title}</h2><p className="mt-4 text-sm leading-7 text-[var(--muted)]">{text}</p><ul className="mt-6 grid gap-3 border-t border-[var(--line)] pt-6 sm:grid-cols-2">{items.map(item=><li key={item} className="flex items-center gap-3 text-sm font-bold"><FiCheck className="shrink-0 text-[#45a0a0]"/>{item}</li>)}</ul></div></article>)}</div></div></section>
  <section className="bg-[#dfeaf2] px-5 py-20 sm:px-8 lg:px-14"><div className="mx-auto grid max-w-[1500px] gap-12 lg:grid-cols-[.65fr_1.35fr]"><div><p className="eyebrow">Süreç</p><h2 className="mt-5 text-4xl font-black tracking-[-.05em]">İlk keşiften son kontrole.</h2><p className="mt-5 text-sm leading-7 text-[var(--muted)]">Her aşama planlı, anlaşılır ve sizinle iletişim halinde ilerler.</p><Link href="/iletisim" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-[#347bb7] px-6 py-4 text-sm font-black text-white">Projenizi konuşalım <FiArrowRight/></Link></div><ol className="overflow-hidden rounded-[26px] bg-white px-6 shadow-sm">{process.map(([no,title,text])=><li key={no} className="grid grid-cols-[52px_1fr] gap-4 border-b border-[var(--line)] py-6 last:border-0 sm:grid-cols-[60px_140px_1fr] sm:items-center"><span className="font-black text-[#347bb7]">{no}</span><h3 className="text-xl font-black">{title}</h3><p className="col-start-2 text-sm leading-6 text-[var(--muted)] sm:col-start-auto">{text}</p></li>)}</ol></div></section>
  <TrustBand/>
  <PrinciplesBand/>
  <ImageCta eyebrow="Projenizi konuşalım" title="Doğru çözüm, doğru planla başlar." text="İhtiyacınızı yerinde değerlendirelim; kapsam, malzeme ve uygulama sürecini birlikte netleştirelim." image="/gumusoglu/hero-gumusoglu-light-v3.webp"/>
</main>}
